{% set name = "progressbar2" %}
{% set version = "3.55.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86835d1f1a9317ab41aeb1da5e4184975e2306586839d66daf63067c102f8f04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python =2.7|>=3.4
    - setuptools
  run:
    - python =2.7|>=3.4
    - python-utils >=2.3.0
    - six

test:
  imports:
    - progressbar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WoLpH/python-progressbar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Progressbar library to provide visual (yet text based) progress to long running operations.
  description: |
    A text progress bar is typically used to display the progress of a long
    running operation, providing a visual cue that processing is underway.

    The ProgressBar class manages the current progress, and the format of the line
    is given by a number of widgets. A widget is an object that may display
    differently depending on the state of the progress bar. There are many types
    of widgets:

     - `Timer`
     - `ETA`
     - `AdaptiveETA`
     - `FileTransferSpeed`
     - `AdaptiveTransferSpeed`
     - `AnimatedMarker`
     - `Counter`
     - `Percentage`
     - `FormatLabel`
     - `SimpleProgress`
     - `Bar`
     - `ReverseBar`
     - `BouncingBar`
     - `RotatingMarker`
     - `DynamicMessage`

    The progressbar module is very easy to use, yet very powerful. It will also
    automatically enable features like auto-resizing when the system supports it.
  doc_url: http://progressbar-2.readthedocs.org/en/latest/
  dev_url: https://github.com/WoLpH/python-progressbar

extra:
  recipe-maintainers:
    - maartenbreddels
    - WoLpH
    - marcelotrevisani
    - BastianZim
