{% set name = "progressbar2" %}
{% set version = "3.42.0" %}
{% set sha256 = "c086fc1f718839c0ec95caaeb7bd5a1d0268a8775960b8f9dee06f2a04c84628" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner >=2.8
    - python-utils
  run:
    - python
    - pytest-runner >=2.8
    - python-utils

test:
  imports:
    - progressbar

about:
  home: https://github.com/WoLpH/python-progressbar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Progressbar library to provide visual (yet text based) progress to long running operations.
  description: |
        A text progress bar is typically used to display the progress of a long
        running operation, providing a visual cue that processing is underway.

        The ProgressBar class manages the current progress, and the format of the line
        is given by a number of widgets. A widget is an object that may display
        differently depending on the state of the progress bar. There are many types
        of widgets:

         - `Timer`
         - `ETA`
         - `AdaptiveETA`
         - `FileTransferSpeed`
         - `AdaptiveTransferSpeed`
         - `AnimatedMarker`
         - `Counter`
         - `Percentage`
         - `FormatLabel`
         - `SimpleProgress`
         - `Bar`
         - `ReverseBar`
         - `BouncingBar`
         - `RotatingMarker`
         - `DynamicMessage`

        The progressbar module is very easy to use, yet very powerful. It will also
        automatically enable features like auto-resizing when the system supports it.
  doc_url: http://progressbar-2.readthedocs.org/en/latest/
  dev_url: https://github.com/WoLpH/python-progressbar

extra:
  recipe-maintainers:
    - maartenbreddels
    - WoLpH
