{% set name = "progressbar2" %}
{% set version = "3.54.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d878893cda2f477c63b5bd0f7f5301f03dd0a81c02554a1f2c5562036369376a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - python-utils >=2.3.0
    - six

test:
  imports:
    - progressbar
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/WoLpH/python-progressbar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Progressbar library to provide visual (yet text based) progress to long running operations.
  description: |
    A text progress bar is typically used to display the progress of a long
    running operation, providing a visual cue that processing is underway.

    The ProgressBar class manages the current progress, and the format of the line
    is given by a number of widgets. A widget is an object that may display
    differently depending on the state of the progress bar. There are many types
    of widgets:

     - `Timer`
     - `ETA`
     - `AdaptiveETA`
     - `FileTransferSpeed`
     - `AdaptiveTransferSpeed`
     - `AnimatedMarker`
     - `Counter`
     - `Percentage`
     - `FormatLabel`
     - `SimpleProgress`
     - `Bar`
     - `ReverseBar`
     - `BouncingBar`
     - `RotatingMarker`
     - `DynamicMessage`

    The progressbar module is very easy to use, yet very powerful. It will also
    automatically enable features like auto-resizing when the system supports it.
  doc_url: http://progressbar-2.readthedocs.org/en/latest/
  dev_url: https://github.com/WoLpH/python-progressbar

extra:
  recipe-maintainers:
    - maartenbreddels
    - WoLpH
    - marcelotrevisani
